<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4bdb004283d51fe56f22a8a0b5d82827
{
    public static $prefixLengthsPsr4 = array (
        'P' =>
        array (
            'Photos\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Photos\\' =>
        array (
            0 => __DIR__ . '/../..' . '/',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4bdb004283d51fe56f22a8a0b5d82827::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4bdb004283d51fe56f22a8a0b5d82827::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit4bdb004283d51fe56f22a8a0b5d82827::$classMap;

        }, null, ClassLoader::class);
    }
}
